### ISSUE TITLE
New Plex Movie Agent breaks plex_top_playlists

### ISSUE THREAD

**Issue by ookla-ariel-ride** [pbrink231/plex_top_playlists#38] opened 2020-08-02 16:15 UTC
It looks like using the new Plex movie agent breaks this script.  The script is able to successfully grab all the movies from my Plex installation, but then is unable to associate IMDB IDs and build the playlists.  This is a snippet of my output showing this behavior.

Retrieving a list of movies from the 'Movies' library in Plex...
Added 20128 movies to your 'all movies' list from the 'Movies' library in Plex...
Found 20128 movies total in 'all movies' list from Plex...
Creating movie dictionary based on ID
[==================================================] 100.0% ...20128 of 20128
cached plex movies
Retrieving new lists
Movies Top Weekly: STARTING TRAKT LIST - TYPE: watched - URL: https://api.trakt.tv/movies/watched/weekly - KIND: playlist
Movies Top Weekly: finding matching movies for playlist with count 80
Movies Top Weekly: list EMPTY so will only be REMOVED and not created
Movies Top Weekly: Playlist made for primary user
Skipping adding to shared users

        0 of 80 found in imdb list:
            Movies Top Weekly
        That means you are MISSING:
            78

**Comment by pbrink231** [comment] 2020-08-07 02:44
Read into this a bunch while fixing up the code.

Please post here to +1 this issue.  Once they expose the ids then I can update this to work with the new media agent which I think is pretty good.
https://forums.plex.tv/t/native-plex-agents-allow-access-to-external-provider-ids-for-media-eg-imdb-tmdb-tvdb/619090

here is a link to my comment if you want to heart it to give it better traction
https://forums.plex.tv/t/native-plex-agents-allow-access-to-external-provider-ids-for-media-eg-imdb-tmdb-tvdb/619090/97?u=pbrink231

For now you will have to keep your media in the agent "Plex Movie (Legacy)".  You can modify it by clicking the `3 dots next to your library -> Manage Library -> Edit...`,  In the new window click `Advanced -> Scroll down to Agent -> Plex Movie (Legacy)`.

Make sure after you make this change you update all meta data `3 dots next to the library -> Manage Library -> Refresh All Metadata`

**Comment by ookla-ariel-ride** [comment] 2020-08-20 14:31
Looks like plex added the needed features to the new media agent.

[PMS 1.20.1.3213 release notes](https://forums.plex.tv/t/plex-media-server/30447/360)

**(Library) Store external ids for items in new Plex Movie libraries.**

**Comment by pbrink231** [comment] 2020-08-23 19:58
Looks good.  Doesn’t say much as far as details.  I’ll have to check out the new beta

**Comment by pbrink231** [comment] 2020-08-23 20:12
Found a comment on the format they did.  Notes for when I can check this out.

```
...
<Guid id="imdb://tt1385826"/>
<Guid id="tmdb://38050"/>
...
```

The main guid is the new Plex agent.  They added these additional into the xml to get the other ids.

So if Plex agent then search these to get the IMDB.  If using TVDB then use that.

**Comment by jalarab** [comment] 2020-08-26 14:36
Maybe this post could help to fix it. 
RG9400
 found the information of the new agent in the database and how to extract it.
https://www.reddit.com/r/PleX/comments/igi2s5/fork_of_plextraktscrobbler_which_is_compatible/g2wd0cv/?utm_source=share&utm_medium=web2x&context=3

**Comment by Azswanepoel** [comment] 2020-12-31 06:42
@pbrink231 

been doing some research. I think here is outlines the beta of this working with the new plex agent

https://forums.plex.tv/t/implemented-native-plex-agents-allow-access-to-external-provider-ids-for-media-eg-imdb-tmdb-tvdb/619090/129

also found this, same topic, but may not be as helpful.
https://www.reddit.com/r/PleX/comments/igi2s5/fork_of_plextraktscrobbler_which_is_compatible/

I really hope this helps you update the script, it would be the highlight of 2020! 

hope to hear form you soon
happy new year

====================

This is so close to what we hope to make happen

https://github.com/banjo/plex-web

====================

update December 2020

https://github.com/Taxel/PlexTraktSync/pull/87

==

**Comment by Mike7154** [comment] 2021-01-05 20:20
I'm an amateur programmer on the side, and it's been a long time since I used github, so I probably did something wrong, but I got mine working for the new agent.

But I made a quick fix for myself until this is fixed by the developer. The problem is the plexapi isnt updated yet to even support this change, I imagine that is the holdup for the fix.

To use my quickfix you need to replace two things.
1. The file 'plex_top_playlists-master\functions\plex_library\movies.py'
2. The entire plexapi folder

The movies.py file I modified is here https://github.com/Mike7154/plex_playlists_new_agent_quickfix

And I just replaced my plexapi folder with the forked one that is complatible with the new agent https://github.com/JonnyWong16/python-plexapi/tree/feature/plex_movie

my plexapi folder was located at C:\Users\mike-\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\plexapi

WARNINGS!: 
- There is a reason that plexapi didn't get updated yet. It has to do with problems with unclaimed servers. This issue didn't apply to me
- I only tested this fix with movies. I don't watch a lot of TV shows, but I don't think that will be impacted at all
- I can't really support this and I consider it a bandaid solution until this repository is updated, and I imagine that will happen when the plexapi updates get resolved. I'm just willing to share my solution.

**Comment by pbrink231** [comment] 2021-01-20 16:43
@Mike7154, thanks for checking this out.  Hopefully I will get a fix by this weekend.  I will pull your branch in to give you credit on the commit.

You can also go to pull requests and request pulling your branch in.  We can comment any issues and then I can easily pull your changes in.  Will also help so your current branch can easily pull in the updates and not get in to merge conflict hell.

**Comment by Azswanepoel** [comment] 2021-01-20 16:58
@pbrink231 - we appreciate you, if we can buy you a coffee or send you some venmo coins, we would love to support you. 

fingers crossed for this weekend. 

Thanks again for everything.

**Comment by Mike7154** [comment] 2021-01-21 14:23
Alright. I made a pull request. I didn't fork it properly so I reforked and pasted in the edits, hopefully all the spaces copied in properly so python will take it. 

Note that it will not run with the existing master branch of plexapi. I hope they update it soon, but it might be confusing for users of this to manually replace the plexapi instead of using pip install. Perhaps just update the development branch and add instructions for people who want to use the new plex agent. Then update when the plexapi works with the new plex agent.

**Comment by pbrink231** [comment] 2021-01-26 03:52
I reviewed the pull request.  Along with the plexapi.

I think the best approach is to keep this on hold till the plexapi becomes official.  The current change may be reverted depending on if plex fixes the issue or says it will stay that way.

@Mike7154 Can you update the requirements.txt file with the proper version of plexapi in your pull request.  I will keep it as a dev branch that people can pull specifically if they want to.  Once the plexapi is confirmed I will pull it to the master.  Thank you for the help.
https://stackoverflow.com/questions/16584552/how-to-state-in-requirements-txt-a-direct-github-source

**Comment by ookla-ariel-ride** [comment] 2021-01-31 05:57
PlexAPI 4.3.0 (released ) now includes support for the new movie agent.  See https://github.com/pkkid/python-plexapi/releases/tag/4.3.0

[#628](https://github.com/pkkid/python-plexapi/pull/628) - Add support for the new Plex Movie agent

**Comment by Neaox** [comment] 2021-03-08 07:41
Any updates on this @pbrink231?

**Comment by pbrink231** [comment] 2021-04-15 18:56
Merged pull requests which will update plex api and work with the new plex agent

**Closed as completed by pbrink231** 2021-04-15 18:56 UTC
Labels: enhancement
