### ISSUE TITLE
WARNING: Skipping movie, using new agent:

### ISSUE THREAD

**Issue by Dex321x** [pbrink231/plex_top_playlists#42] opened 2020-10-08 20:13 UTC
I recently noticed that the script stopped working. 
Maybe it has to do something with a Plex update (I'm running Version 1.20.2.3402 and I need to use "Plex Movie" as a Scanner/Agent. The new Plex Legacy Scanner does not work for me (can not recognize a movie). 

> Creating movie dictionary based on IMDB ID
> WARNING: Skipping movie, using new agent: 8--------] 0.6% ...9 of 1594
> WARNING: Skipping movie, using new agent: 10 Minutes Gone ...13 of 1594
> WARNING: Skipping movie, using new agent: 13 Assassins.1% ...17 of 1594
> WARNING: Skipping movie, using new agent: 30 über Nacht9% ...30 of 1594
>....

and when creating the playlists i get this:

> Movies Top Weekly: finding matching movies for playlist with count 80
> ERROR - cannot delete playlist: Movies Top Weekly
> Movies Top Weekly: Playlist made for primary user
>

Would be very nice if you can have a look at it! Thank you!

**Comment by Azswanepoel** [comment] 2020-12-31 06:59
@pbrink231 

been doing some research. I think here is outlines the beta of this working with the new plex agent

https://forums.plex.tv/t/implemented-native-plex-agents-allow-access-to-external-provider-ids-for-media-eg-imdb-tmdb-tvdb/619090/129

also found this, same topic, but may not be as helpful.
https://www.reddit.com/r/PleX/comments/igi2s5/fork_of_plextraktscrobbler_which_is_compatible/

I really hope this helps you update the script, it would be the highlight of 2020! 

hope to hear form you soon
happy new year

====================

update December 2020

https://github.com/Taxel/PlexTraktSync/pull/87

==

**Comment by Mike7154** [comment] 2021-01-04 19:16
Having the same issue, although I don't have time to dig in and figure it out on my own for the next few months. This script seems awesome and i want to use it.

**Comment by Mike7154** [comment] 2021-01-04 19:32
Actually. I believe you can just revert your library back to plex legacy. But "Fix match" for the item that isn't matching and choose the new agent for that one item. It would just be skipped by this script.

**Comment by pbrink231** [comment] 2021-01-20 16:39
You can set your library to be plex agent (legacy) and then do a full library analyze.  This will make all movies be usable with this.  When you change your library to the new plex media, only new movies added will be using the new plex agent so will still work for old ones.

This isnt a hard change.  just have not had time to fix it.  hopefully this weekend I will finally fix it to work with the new agent

**Comment by pbrink231** [comment] 2021-01-20 16:46
duplicate of #38

**Closed as completed by pbrink231** 2021-01-20 16:46 UTC
